name: Build Flet APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Flet
        run: pip install flet

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # latest stable supported by Flet

      - name: Build APK
        run: flet build apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: BAC_DZ-apk
          path: build/*
