name: Build Flet APK

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install/upgrade Flet CLI
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flet flet-cli

      - name: Setup Flutter (base version)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Switch Flutter to a supported release (tries several tags)
        run: |
          echo "FLUTTER_ROOT is: $FLUTTER_ROOT"
          cd "$FLUTTER_ROOT"
          git fetch --tags --force
          # Try a list of known-good tags (adjust order if you prefer another)
          for tag in 3.32.8 3.32.6 3.32.3 3.31.0-0.1.pre 3.31.0-0.0.pre; do
            echo "Trying tag: $tag"
            if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
              git checkout "refs/tags/$tag" -q
              echo "Checked out tag $tag"
              break
            fi
            # try remote branch if tag missing
            if git ls-remote --heads origin "$tag" | grep -q "$tag"; then
              git checkout "origin/$tag" -q
              echo "Checked out origin/$tag"
              break
            fi
          done
          # show the flutter version to confirm
          ./bin/flutter --version || flutter --version

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Ensure Flutter packages
        run: |
          cd $GITHUB_WORKSPACE
          flutter pub get || true

      - name: Build APK with Flet
        run: |
          cd $GITHUB_WORKSPACE
          # if your entrypoint is main.py in repo root:
          flet build apk --release
          # If your entrypoint is in another module, uncomment & edit:
          # flet build apk --release --module-name path.to.module

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/**
